apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-api-service-account
  annotations:
    # Replace with your IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_IAM_ROLE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-api
  labels:
    app: s3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-api
  template:
    metadata:
      labels:
        app: s3-api
    spec:
      serviceAccountName: s3-api-service-account
      containers:
      - name: s3-api
        image: your-registry/s3-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: s3-api-config
        # No AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY needed for IRSA
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/debug/s3
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/debug/s3
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: s3-api-service
spec:
  selector:
    app: s3-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
